document.writeln("<ul class=\'navbar-nav ml-auto\'>");
document.writeln("                        <li class=\'nav-item\'>");
document.writeln("                            <a class=\'nav-link\' href=\'index.html\'>Home</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'nav-item\'>");
document.writeln("                            <a href=\'overview.html\' class=\'nav-link\' >Overview</a>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'dropdown nav-item\'>");
document.writeln("                            <a href=\'#\' class=\'nav-link\' data-toggle=\'dropdown\'>Members");
document.writeln("                                <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu agile_short_dropdown\'>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'members.html?tab=teachers\'>Teachers</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'members.html?tab=phds\'>Ph.D Candidates</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'members.html?tab=masters\'>Master Candidates</a>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'dropdown nav-item\'>");
document.writeln("                            <a href=\'#\' class=\'nav-link\' data-toggle=\'dropdown\'>Publications");
document.writeln("                                <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu agile_short_dropdown\'>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'publications.html?tab=awards\'>Awards</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'publications.html?tab=publications\'>Publications</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'publications.html?tab=patents\'>Patents</a>");
document.writeln("                                </li>");
document.writeln("");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("                        <li class=\'dropdown nav-item\'>");
document.writeln("                            <a href=\'#\' class=\'nav-link\' data-toggle=\'dropdown\'>Projects");
document.writeln("                                <b class=\'caret\'></b>");
document.writeln("                            </a>");
document.writeln("                            <ul class=\'dropdown-menu agile_short_dropdown\'>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'projects.html?tab=projects_finished\'>Finished Projects</a>");
document.writeln("                                </li>");
document.writeln("                                <li>");
document.writeln("                                    <a href=\'projects.html?tab=projects_goingon\'>Projects Going On</a>");
document.writeln("                                </li>");
document.writeln("");
document.writeln("                            </ul>");
document.writeln("                        </li>");
document.writeln("						<li class=\'nav-item\'>");
document.writeln("							<a href=\'news.html\' class=\'nav-link\' >News</a>");
document.writeln("						</li>");
document.writeln("");
document.writeln("                        <li class=\'nav-item\'>");
document.writeln("                            <a href=\'Recruitment.html\' class=\'nav-link\' >Recruitment</a>");
document.writeln("                        </li>");
document.writeln("                    </ul>");